"""Exercises ParseReplay.parse_battle against real Showdown protocol logs
generated by the /ch self-play harness. Rather than assert exact kill counts
(which vary per game), it checks structural invariants that must hold for any
correctly parsed battle, across a large sample. A focused synthetic test also
covers Illusion (Zoroark) kill re-attribution, which the self-play logs don't
exercise."""
import glob
import os
import random
import unittest

from ParseReplay import parse_battle


# A disguised Illusion mon KOs before the disguise breaks; the KO must end up on
# the real Zoroark, not the copied mon.
ILLUSION_LOG = """|player|p1|Alice|
|player|p2|Bob|
|poke|p1|Pikachu, M|
|poke|p1|Zoroark-Hisui, M|
|poke|p2|Snorlax, M|
|poke|p2|Blissey, F|
|teampreview
|start
|switch|p1a: Zoro Decoy|Pikachu, M|100/100
|switch|p2a: Snorlax|Snorlax, M|100/100
|turn|1
|move|p1a: Zoro Decoy|Thunderbolt|p2a: Snorlax
|-damage|p2a: Snorlax|0 fnt
|faint|p2a: Snorlax
|switch|p2a: Blissey|Blissey, F|100/100
|turn|2
|move|p2a: Blissey|Body Slam|p1a: Zoro Decoy
|-damage|p1a: Zoro Decoy|40/100
|replace|p1a: Real Zoro|Zoroark-Hisui, M
|-end|p1a: Real Zoro|Illusion
|move|p1a: Real Zoro|Night Daze|p2a: Blissey
|-damage|p2a: Blissey|0 fnt
|faint|p2a: Blissey
|win|Alice""".split("\n")

CH_LOGS = r"C:\Users\001\ch\harness\logs"


def _load(path):
    with open(path, encoding="utf-8") as f:
        return f.read().split("\n")


def _sample_logs(n=300, seed=0):
    paths = glob.glob(os.path.join(CH_LOGS, "**", "*.log"), recursive=True)
    paths = [p for p in paths if any(l.startswith("|win|") for l in _load(p))]
    random.Random(seed).shuffle(paths)
    return paths[:n]


class ParseBattleInvariants(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.paths = _sample_logs()
        if not cls.paths:
            raise unittest.SkipTest(f"no completed logs found under {CH_LOGS}")

    def test_invariants(self):
        checked = 0
        for path in self.paths:
            log = _load(path)
            battle = parse_battle(log)
            with self.subTest(log=os.path.basename(path)):
                # A completed game names a winner and a loser.
                self.assertIsNotNone(battle.winner, "no winner parsed")
                self.assertIsNotNone(battle.loser, "no loser parsed")
                self.assertIsNot(battle.winner, battle.loser)

                for side in (battle.winner, battle.loser):
                    for mon in side.team:
                        self.assertGreaterEqual(mon.direct_kills, 0)
                        self.assertGreaterEqual(mon.indirect_kills, 0)

                win_alive = sum(1 for m in battle.winner.team if not m.ko)
                lose_alive = sum(1 for m in battle.loser.team if not m.ko)
                # The winner never ends with fewer live Pokemon than the loser.
                # (Both can reach zero: a last mon can KO the loser's last mon
                # and then faint to its own recoil/Life Orb after the win.)
                self.assertGreaterEqual(win_alive, lose_alive,
                                        "winner has fewer survivors than loser")

                deaths = sum(m.ko for m in battle.winner.team) + \
                    sum(m.ko for m in battle.loser.team)
                kills = sum(m.kills for m in battle.winner.team) + \
                    sum(m.kills for m in battle.loser.team)
                # Every credited kill corresponds to a faint; self-KOs and
                # unattributed faints mean kills can only ever be <= deaths.
                self.assertLessEqual(kills, deaths,
                                     f"{kills} kills > {deaths} deaths")
            checked += 1
        print(f"\nchecked {checked} battles")

    def test_stats_are_populated(self):
        """Across the sample, the parser must actually credit kills -- a parser
        that silently produced all zeros would pass the <= invariant."""
        total_direct = total_indirect = 0
        for path in self.paths:
            battle = parse_battle(_load(path))
            if battle.winner is None:
                continue
            for side in (battle.winner, battle.loser):
                for mon in side.team:
                    total_direct += mon.direct_kills
                    total_indirect += mon.indirect_kills
        print(f"\ntotals across sample: {total_direct} direct, {total_indirect} indirect")
        self.assertGreater(total_direct, 0)
        self.assertGreater(total_indirect, 0)


class IllusionReattribution(unittest.TestCase):
    def test_disguised_ko_moves_to_zoroark(self):
        battle = parse_battle(ILLUSION_LOG)
        team = {m.species: m for m in battle.winner.team}
        # The KO scored while disguised as Pikachu, plus the post-reveal KO,
        # both belong to Zoroark; Pikachu keeps nothing.
        self.assertEqual(team["Pikachu"].kills, 0)
        self.assertEqual(team["Zoroark-Hisui"].direct_kills, 2)


if __name__ == "__main__":
    unittest.main(verbosity=2)
